-- GameTracker schema
-- Run once in Supabase SQL Editor (or via `npm run migrate`).

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------- profiles
create table if not exists public.profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  username     text unique not null,
  display_name text,
  bio          text,
  avatar_url   text,
  accent       text not null default '#8b5cf6',
  is_public    boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

comment on table public.profiles is 'Public player profile, one row per auth user.';

-- ------------------------------------------------------------------- games
create table if not exists public.games (
  id                 bigint generated by default as identity primary key,
  steam_appid        bigint unique not null,
  name               text not null,
  header_image       text,
  background_image   text,
  capsule_image      text,
  library_image      text,
  release_date       date,
  developers         text[] not null default '{}',
  publishers         text[] not null default '{}',
  genres             text[] not null default '{}',
  platforms          text[] not null default '{}',
  short_description  text,
  metacritic         int,
  price              text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index if not exists games_name_idx on public.games (lower(name));

-- --------------------------------------------------------- collection items
create table if not exists public.collection_items (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references public.profiles (id) on delete cascade,
  game_id      bigint not null references public.games (id) on delete cascade,
  status       text not null default 'backlog'
                 check (status in ('backlog', 'playing', 'completed', 'dropped')),
  rating       int check (rating is null or rating between 0 and 10),
  hours_played numeric(8, 2) check (hours_played is null or hours_played >= 0),
  finished_at  date,
  notes        text,
  is_favorite  boolean not null default false,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (user_id, game_id)
);

create index if not exists collection_items_user_idx on public.collection_items (user_id);
create index if not exists collection_items_game_idx on public.collection_items (game_id);

-- --------------------------------------------------------------- categories
create table if not exists public.categories (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references public.profiles (id) on delete cascade,
  name       text not null,
  color      text not null default '#8b5cf6',
  icon       text not null default 'folder',
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.category_items (
  category_id bigint not null references public.categories (id) on delete cascade,
  item_id     bigint not null references public.collection_items (id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (category_id, item_id)
);

-- --------------------------------------------------------------- tier lists
create table if not exists public.tier_lists (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references public.profiles (id) on delete cascade,
  name        text not null,
  description text,
  theme       text not null default 'nebula',
  is_public   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists tier_lists_user_idx on public.tier_lists (user_id);

alter table public.tier_lists add column if not exists friends_visible boolean not null default false;

create table if not exists public.tier_rows (
  id           bigint generated by default as identity primary key,
  tier_list_id bigint not null references public.tier_lists (id) on delete cascade,
  key          text not null,
  label        text not null,
  color        text not null default '#64748b',
  sort_order   int not null default 0,
  unique (tier_list_id, key)
);

create table if not exists public.tier_items (
  id         bigint generated by default as identity primary key,
  tier_row_id bigint not null references public.tier_rows (id) on delete cascade,
  game_id    bigint not null references public.games (id) on delete cascade,
  position   int not null default 0
);

create index if not exists tier_items_row_idx on public.tier_items (tier_row_id);
create index if not exists tier_items_game_idx on public.tier_items (game_id);

-- ----------------------------------------------------------------- friends
-- One row per directed request. A pair is kept unique by user_id/friend_id and the
-- add_friend() RPC refuses to create the mirrored row, so a pair has at most one edge.
create table if not exists public.friendships (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references public.profiles (id) on delete cascade,
  friend_id   uuid not null references public.profiles (id) on delete cascade,
  status      text not null default 'pending' check (status in ('pending', 'accepted')),
  created_at  timestamptz not null default now(),
  accepted_at timestamptz,
  unique (user_id, friend_id),
  check (user_id <> friend_id)
);

create index if not exists friendships_user_idx on public.friendships (user_id);
create index if not exists friendships_friend_idx on public.friendships (friend_id);

-- ------------------------------------------------------- profile showcase
-- The "featured shelf" on a profile: a handful of collection games pinned by the owner.
create table if not exists public.profile_showcase (
  user_id    uuid not null references public.profiles (id) on delete cascade,
  game_id    bigint not null references public.games (id) on delete cascade,
  position   int not null default 0,
  created_at timestamptz not null default now(),
  primary key (user_id, game_id)
);

-- nickname: unique, case-insensitive, Steam-like rules
create unique index if not exists profiles_username_unique on public.profiles (lower(username));

alter table public.profiles
  drop constraint if exists profiles_username_format;
alter table public.profiles
  add constraint profiles_username_format
  check (username ~ '^[A-Za-z0-9_]{3,20}$') not valid;

-- ------------------------------------------------------------ triggers
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists games_touch on public.games;
create trigger games_touch before update on public.games
for each row execute function public.touch_updated_at();

drop trigger if exists collection_items_touch on public.collection_items;
create trigger collection_items_touch before update on public.collection_items
for each row execute function public.touch_updated_at();

drop trigger if exists tier_lists_touch on public.tier_lists;
create trigger tier_lists_touch before update on public.tier_lists
for each row execute function public.touch_updated_at();

-- auto-create a profile whenever a new auth user signs up
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  base      text;
  candidate text;
  suffix    int := 0;
begin
  base := coalesce(
    nullif(trim(new.raw_user_meta_data ->> 'username'), ''),
    split_part(coalesce(new.email, 'player'), '@', 1),
    'player'
  );
  base := regexp_replace(base, '[^A-Za-z0-9_]', '', 'g');
  if length(base) < 3 then
    base := base || 'player';
  end if;
  base := left(base, 16);

  candidate := base;
  while exists (select 1 from public.profiles where lower(username) = lower(candidate)) loop
    suffix := suffix + 1;
    candidate := left(base, 20 - length(suffix::text)) || suffix::text;
  end loop;

  insert into public.profiles (id, username, display_name)
  values (new.id, candidate, candidate);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- --------------------------------------------------------- upsert helper
create or replace function public.upsert_games(rows jsonb)
returns setof public.games
language plpgsql
security definer
set search_path = public
as $$
begin
  -- RETURN QUERY is required: a bare INSERT ... RETURNING discards its rows in PL/pgSQL.
  return query
  insert into public.games (
    steam_appid, name, header_image, background_image, capsule_image, library_image,
    release_date, developers, publishers, genres, platforms,
    short_description, metacritic, price
  )
  select
    (item ->> 'steam_appid')::bigint,
    coalesce(nullif(item ->> 'name', ''), 'Unknown'),
    item ->> 'header_image',
    item ->> 'background_image',
    item ->> 'capsule_image',
    item ->> 'library_image',
    nullif(item ->> 'release_date', '')::date,
    coalesce(array(select jsonb_array_elements_text(coalesce(item -> 'developers', '[]'::jsonb))), '{}'),
    coalesce(array(select jsonb_array_elements_text(coalesce(item -> 'publishers', '[]'::jsonb))), '{}'),
    coalesce(array(select jsonb_array_elements_text(coalesce(item -> 'genres', '[]'::jsonb))), '{}'),
    coalesce(array(select jsonb_array_elements_text(coalesce(item -> 'platforms', '[]'::jsonb))), '{}'),
    coalesce(item ->> 'short_description', ''),
    nullif(item ->> 'metacritic', '')::int,
    nullif(item ->> 'price', '')
  from jsonb_array_elements(rows) as item
  on conflict (steam_appid) do update set
    name              = excluded.name,
    header_image      = excluded.header_image,
    background_image  = excluded.background_image,
    capsule_image     = excluded.capsule_image,
    library_image     = excluded.library_image,
    release_date      = excluded.release_date,
    developers        = excluded.developers,
    publishers        = excluded.publishers,
    genres            = excluded.genres,
    platforms         = excluded.platforms,
    short_description = excluded.short_description,
    metacritic        = excluded.metacritic,
    price             = excluded.price,
    updated_at        = now()
  returning *;
end;
$$;

revoke all on function public.upsert_games(jsonb) from public;
grant execute on function public.upsert_games(jsonb) to anon, authenticated;

-- tier list save (replace rows + items atomically)
create or replace function public.save_tier_list(
  p_tier_list_id bigint,
  p_rows jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  row_data jsonb;
  new_row_id bigint;
begin
  if not exists (
    select 1 from public.tier_lists
    where id = p_tier_list_id and user_id = auth.uid()
  ) then
    raise exception 'not your tier list';
  end if;

  delete from public.tier_rows where tier_list_id = p_tier_list_id;

  for row_data in select * from jsonb_array_elements(p_rows)
  loop
    insert into public.tier_rows (tier_list_id, key, label, color, sort_order)
    values (
      p_tier_list_id,
      coalesce(row_data ->> 'key', 'row'),
      coalesce(row_data ->> 'label', 'Row'),
      coalesce(row_data ->> 'color', '#64748b'),
      coalesce((row_data ->> 'sort_order')::int, 0)
    )
    returning id into new_row_id;

    insert into public.tier_items (tier_row_id, game_id, position)
    select new_row_id, (entry ->> 'game_id')::bigint, (entry ->> 'position')::int
    from jsonb_array_elements(coalesce(row_data -> 'items', '[]'::jsonb)) as entry
    where exists (select 1 from public.games where id = (entry ->> 'game_id')::bigint);
  end loop;

  update public.tier_lists set updated_at = now() where id = p_tier_list_id;
end;
$$;

grant execute on function public.save_tier_list(bigint, jsonb) to authenticated;

-- ------------------------------------------------------------ friends
-- Visibility rule used by every "someone else's data" path: public profile,
-- the owner, or an accepted friend.
create or replace function public.can_view_profile(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = p_user_id
      and (
        p.is_public
        or p.id = auth.uid()
        or exists (
          select 1 from public.friendships f
          where f.status = 'accepted'
            and (
              (f.user_id = auth.uid() and f.friend_id = p_user_id)
              or (f.friend_id = auth.uid() and f.user_id = p_user_id)
            )
        )
      )
  );
$$;

revoke all on function public.can_view_profile(uuid) from public;
grant execute on function public.can_view_profile(uuid) to anon, authenticated;

-- Nickname availability for the signup form. Existence of a nickname is implied by it
-- being a unique public identifier, so leaking a boolean here is not a real disclosure.
create or replace function public.username_available(p_username text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select trim(coalesce(p_username, '')) ~ '^[A-Za-z0-9_]{3,20}$'
     and not exists (
       select 1 from public.profiles where lower(username) = lower(trim(p_username))
     );
$$;

revoke all on function public.username_available(text) from public;
grant execute on function public.username_available(text) to anon, authenticated;

-- Sends (or auto-accepts) a friend request. Returns a short status for the UI.
create or replace function public.add_friend(p_username text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  target   uuid;
  existing text;
begin
  if auth.uid() is null then
    return 'unauthorized';
  end if;

  select id into target from public.profiles where lower(username) = lower(p_username);
  if target is null then return 'not_found'; end if;
  if target = auth.uid() then return 'self'; end if;

  select f.status into existing
  from public.friendships f
  where (f.user_id = auth.uid() and f.friend_id = target)
     or (f.user_id = target and f.friend_id = auth.uid())
  limit 1;

  if existing = 'accepted' then return 'friends'; end if;
  if existing = 'pending' then
    -- They already asked us: treat this click as an accept instead of dead-ending.
    update public.friendships
    set status = 'accepted', accepted_at = now()
    where status = 'pending'
      and ((user_id = auth.uid() and friend_id = target) or (user_id = target and friend_id = auth.uid()));
    return 'friends';
  end if;

  insert into public.friendships (user_id, friend_id) values (auth.uid(), target);
  return 'pending';
end;
$$;

-- Supabase grants EXECUTE on new public-schema functions to anon/authenticated via
-- ALTER DEFAULT PRIVILEGES, so PUBLIC-only revokes are not enough here.
revoke all on function public.add_friend(text) from public, anon;
grant execute on function public.add_friend(text) to authenticated;

create or replace function public.respond_friend(p_friendship_id bigint, p_accept boolean)
returns text
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    return 'unauthorized';
  end if;

  if p_accept then
    update public.friendships
    set status = 'accepted', accepted_at = now()
    where id = p_friendship_id and friend_id = auth.uid() and status = 'pending';
    if found then return 'accepted'; end if;
    return 'forbidden';
  end if;

  delete from public.friendships
  where id = p_friendship_id
    and ((friend_id = auth.uid()) or (user_id = auth.uid()));
  if found then return 'removed'; end if;
  return 'forbidden';
end;
$$;

revoke all on function public.respond_friend(bigint, boolean) from public, anon;
grant execute on function public.respond_friend(bigint, boolean) to authenticated;

-- ------------------------------------------------------------------- RLS
alter table public.profiles        enable row level security;
alter table public.games           enable row level security;
alter table public.collection_items enable row level security;
alter table public.categories      enable row level security;
alter table public.category_items  enable row level security;
alter table public.tier_lists      enable row level security;
alter table public.tier_rows       enable row level security;
alter table public.tier_items      enable row level security;
alter table public.friendships     enable row level security;
alter table public.profile_showcase enable row level security;

-- profiles: readable when public, when it's you, or when you're accepted friends.
-- security-definer helper avoids infinite recursion into the friendships policy.
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
for select using (public.can_view_profile(id));

drop policy if exists profiles_insert_self on public.profiles;
create policy profiles_insert_self on public.profiles
for insert with check (auth.uid() = id);

drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles
for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists profiles_delete_self on public.profiles;
create policy profiles_delete_self on public.profiles
for delete using (auth.uid() = id);

-- games: shared catalog. Reads are public, but writes go only through the
-- security-definer upsert_games() RPC - keep raw writes closed even for anon.
drop policy if exists games_select on public.games;
create policy games_select on public.games for select using (true);

drop policy if exists games_insert on public.games;
create policy games_insert on public.games
for insert to authenticated with check (auth.role() = 'authenticated');

drop policy if exists games_update on public.games;
create policy games_update on public.games
for update to authenticated using (auth.role() = 'authenticated');

-- collection items: full access for the owner, nothing readable for anyone else.
-- Everyone else reads through profile_collection(), which deliberately omits private
-- fields such as notes and respects profiles_select / friendships.
drop policy if exists collection_items_own on public.collection_items;
create policy collection_items_own on public.collection_items
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.profile_collection(p_username text)
returns setof jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'id', ci.id,
    'status', ci.status,
    'rating', ci.rating,
    'hours_played', ci.hours_played,
    'is_favorite', ci.is_favorite,
    'finished_at', ci.finished_at,
    'created_at', ci.created_at,
    'updated_at', ci.updated_at,
    'game', jsonb_build_object(
      'id', g.id,
      'steam_appid', g.steam_appid,
      'name', g.name,
      'header_image', g.header_image,
      'capsule_image', g.capsule_image,
      'background_image', g.background_image,
      'genres', g.genres
    )
  )
  from public.collection_items ci
  join public.games g on g.id = ci.game_id
  join public.profiles p on p.id = ci.user_id
  where lower(p.username) = lower(p_username)
    and public.can_view_profile(ci.user_id)
  order by ci.updated_at desc;
$$;

revoke all on function public.profile_collection(text) from public;
grant execute on function public.profile_collection(text) to anon, authenticated;

create or replace function public.profile_showcase_games(p_username text)
returns setof jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'user_id', s.user_id,
    'game_id', s.game_id,
    'position', s.position,
    'game', jsonb_build_object(
      'id', g.id,
      'steam_appid', g.steam_appid,
      'name', g.name,
      'header_image', g.header_image,
      'capsule_image', g.capsule_image,
      'genres', g.genres,
      'release_date', g.release_date
    )
  )
  from public.profile_showcase s
  join public.games g on g.id = s.game_id
  join public.profiles p on p.id = s.user_id
  where lower(p.username) = lower(p_username)
    and public.can_view_profile(s.user_id)
  order by s.position asc;
$$;

revoke all on function public.profile_showcase_games(text) from public;
grant execute on function public.profile_showcase_games(text) to anon, authenticated;


-- categories
drop policy if exists categories_own on public.categories;
create policy categories_own on public.categories
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists category_items_own on public.category_items;
create policy category_items_own on public.category_items
for all using (
  exists (
    select 1 from public.categories c
    where c.id = category_id and c.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.categories c
    where c.id = category_id and c.user_id = auth.uid()
  )
);

-- friendships: you can see and manage the edges you are part of. Requests are created
-- through add_friend(), which refuses self-edges and mirrored duplicates.
drop policy if exists friendships_select on public.friendships;
create policy friendships_select on public.friendships
for select using (auth.uid() = user_id or auth.uid() = friend_id);

drop policy if exists friendships_write on public.friendships;
create policy friendships_write on public.friendships
for all
using (auth.uid() = user_id or auth.uid() = friend_id)
with check (auth.uid() = user_id or auth.uid() = friend_id);

-- showcase: readable through the same visibility rule, writable only by the owner
drop policy if exists profile_showcase_select on public.profile_showcase;
create policy profile_showcase_select on public.profile_showcase
for select using (public.can_view_profile(user_id));

drop policy if exists profile_showcase_write on public.profile_showcase;
create policy profile_showcase_write on public.profile_showcase
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- tier lists
drop policy if exists tier_lists_select on public.tier_lists;
create policy tier_lists_select on public.tier_lists
for select using (
  is_public
  or auth.uid() = user_id
  or (friends_visible and public.can_view_profile(user_id))
);

drop policy if exists tier_lists_insert on public.tier_lists;
create policy tier_lists_insert on public.tier_lists
for insert with check (auth.uid() = user_id);

drop policy if exists tier_lists_update on public.tier_lists;
create policy tier_lists_update on public.tier_lists
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists tier_lists_delete on public.tier_lists;
create policy tier_lists_delete on public.tier_lists
for delete using (auth.uid() = user_id);

-- tier rows
drop policy if exists tier_rows_select on public.tier_rows;
create policy tier_rows_select on public.tier_rows
for select using (
  exists (
    select 1 from public.tier_lists t
    where t.id = tier_list_id and (t.is_public or t.user_id = auth.uid())
  )
);

drop policy if exists tier_rows_write on public.tier_rows;
create policy tier_rows_write on public.tier_rows
for all using (
  exists (
    select 1 from public.tier_lists t
    where t.id = tier_list_id and t.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.tier_lists t
    where t.id = tier_list_id and t.user_id = auth.uid()
  )
);

-- tier items
drop policy if exists tier_items_select on public.tier_items;
create policy tier_items_select on public.tier_items
for select using (
  exists (
    select 1 from public.tier_rows r
    join public.tier_lists t on t.id = r.tier_list_id
    where r.id = tier_row_id and (t.is_public or t.user_id = auth.uid())
  )
);

drop policy if exists tier_items_write on public.tier_items;
create policy tier_items_write on public.tier_items
for all using (
  exists (
    select 1 from public.tier_rows r
    join public.tier_lists t on t.id = r.tier_list_id
    where r.id = tier_row_id and t.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.tier_rows r
    join public.tier_lists t on t.id = r.tier_list_id
    where r.id = tier_row_id and t.user_id = auth.uid()
  )
);
